# Generated by Django 5.1.2 on 2024-12-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_rename_user_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('super admin', 'Super Admin')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
